import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>HELLO SOVTECH! MEET DANIELA 🙋🏻‍♀️</h1>

        <p className={styles.description}>
          "A man can succeed at almost anything for which he has unlimited
          enthusiasm."—Charles Schwab
        </p>

        <div className={styles.grid}>
          <a href="/who" className={styles.card}>
            <h2>The WHO&rarr;</h2>
            <ul>
              <li>I set goals for myself and work hard to achieve them🥅</li>
              <li>I enjoy being active, with a swim, walk, or run🤸</li>
              <li>Family woman👨‍👩‍👦</li>
              <li>I am curious, creative, and an out-of-the-box thinker🎨</li>
              <li>I simplify practices using a solution-based approach🔦</li>
              <li>I come from a medical background🩹</li>
              <li>I'm pretty good at Foosball⚽</li>
            </ul>
          </a>

          <a href="/why" className={styles.card}>
            <h2>The WHY&rarr;</h2>
            <ul>
              <li>Software development embodies innovation👩🏼‍🎓</li>
              <li>It will challenge my curiosity and creativity🔍</li>
              <li>
                I’m looking to adapt my skills in client and project
                management🗃
              </li>
              <li>
                The Graduate Programme is an amazing entry point for me into
                Tech🎓{" "}
              </li>
              <li>
                I am drawn to the dynamic nature and supportive environment🙌
              </li>
              <li>
                The program will allow me to take the time to harvest my
                technical skills👩‍🌾
              </li>
            </ul>
          </a>

          <a className={styles.card}>
            <h2>Work Experience</h2>
            <table cellSpacing="10">
              <tbody>
                <tr>
                  <td>2016</td>
                  <td>Practice Manager</td>
                </tr>
                <tr>
                  <td>2015</td>
                  <td>Locum OT</td>
                </tr>
                <tr>
                  <td>2013</td>
                  <td>Junior OT</td>
                </tr>
                <tr>
                  <td>2012</td>
                  <td>Community Service </td>
                </tr>
              </tbody>
            </table>
          </a>
 
          <a className={styles.card}>
            <h2>Technical Skills</h2>
            <table cellSpacing="10">
              <tbody>
              <tr>
                <td>Github</td>
                <td>⭐⭐⭐</td>
              </tr>
              <tr>
                <td>Ruby</td>
                <td>⭐⭐⭐</td>
              </tr>
              <tr>
                <td>HTML</td>
                <td>⭐⭐</td>
              </tr>
              <tr>
                <td>Rails</td>
                <td>⭐⭐⭐</td>
              </tr>
              </tbody>
            </table>
          </a>
          

          <a className={styles.card}>
            <h2>Soft Skills</h2>
            <table cellSpacing="10">
              <tbody>
              <tr>
                <td>Communication</td>
                <td>⭐⭐⭐⭐⭐</td>
              </tr>
              <tr>
                <td>Client Mx</td>
                <td>⭐⭐⭐⭐⭐</td>
              </tr>
              <tr>
                <td>Project Mx</td>
                <td>⭐⭐⭐⭐</td>
              </tr>
              <tr>
                <td>Analytical</td>
                <td>⭐⭐⭐⭐</td>
              </tr>
              </tbody>
            </table>
          </a>

          <a className={styles.card}>
            <h2>Interests & Traits</h2>
            <table cellSpacing="10">
              <tbody>
                <tr>
                  <td>Reading</td>
                  <td>Empathetic</td>
                </tr>
                <tr>
                  <td>Exercise</td>
                  <td>Creative</td>
                </tr>
                <tr>
                  <td>Puzzles</td>
                  <td>Lateral Thinker</td>
                </tr>
                <tr>
                  <td>Travel</td>
                  <td>Resouceful</td>
                </tr>
              </tbody>
            </table>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
