import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>HELLO SOVTECH! MEET DANIELA 🙋🏻‍♀️</h1>

        <p className={styles.description}>
          "A man can succeed at almost anything for which he has unlimited
          enthusiasm."—Charles Schwab
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>The WHO&rarr;</h2>
            <p>
              <ul>
                <li>🥅I set goals for myself and work hard to achieve them.</li>
                <li>🤸I enjoy being active, with a swim, walk, or run.</li>
                <li>👨‍👩‍👦Family woman</li>
                <li>
                  🎨I am curious, creative, and an out-of-the-box thinker.
                </li>
                <li>
                  🌍I am proud of my Portuguese roots and South African
                  heritage.{" "}
                </li>
                <li>🔦I simplify practices using a solution-based approach.</li>
                <li>🩹I come from a medical background.</li>
                <li>⚽I'm pretty good at Foosball.</li>
              </ul>
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>The WHY&rarr;</h2>
            <p>
              <ul>
                <li>👩🏼‍🎓Software development embodies innovation.</li>
                <li>🔍It will challenge my curiosity and creativity.</li>
                <li>
                  🗃I’m looking to adapt my skills in client and project
                  management.
                </li>
                <li>
                  🎓The Graduate Programme is an amazing entry point for me into
                  Tech.{" "}
                </li>
                <li>
                  🙌I am drawn to the dynamic nature and supportive environment
                </li>
                <li>
                  👩‍🌾The program will allow me to take the time to harvest my
                  technical skills.
                </li>
              </ul>
            </p>
          </a>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Work Experience</h2>
            <p>
              <table cellspacing="10">
                <tr>
                  <td>2016</td>
                  <td>Practice Manager</td>
                </tr>
                <tr>
                  <td>2015</td>
                  <td>Locum OT</td>
                </tr>
                <tr>
                  <td>2013</td>
                  <td>Junior OT</td>
                </tr>
                <tr>
                  <td>2012</td>
                  <td>Community Service </td>
                </tr>
              </table>
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Interests & Traits&rarr;</h2>
            <p>
              <table cellspacing="10">
                <tr>
                  <td>Reading</td>
                  <td>Empathy</td>
                </tr>
                <tr>
                  <td>Exercise</td>
                  <td>Creativity</td>
                </tr>
                <tr>
                  <td>Puzzles</td>
                  <td>Helpful</td>
                </tr>
                <tr>
                  <td>Travel</td>
                  <td>Resouceful</td>
                </tr>
              </table>
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Soft Skills&rarr;</h2>
            <p>
              <table cellspacing="10">
                <tr>
                  <td>Communication</td>
                  <td>⭐⭐⭐⭐</td>
                </tr>
                <tr>
                  <td>Client Mx</td>
                  <td>⭐⭐⭐⭐⭐</td>
                </tr>
                <tr>
                  <td>Project Mx</td>
                  <td>⭐⭐⭐⭐</td>
                </tr>
                <tr>
                  <td>Analytical</td>
                  <td>⭐⭐⭐⭐</td>
                </tr>
              </table>
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Technical Skills&rarr;</h2>
            <p>
              <table cellspacing="10">
                <tr>
                  <td>Github</td>
                  <td>⭐⭐⭐⭐</td>
                </tr>
                <tr>
                  <td>Ruby</td>
                  <td>⭐⭐⭐</td>
                </tr>
                <tr>
                  <td>HTML</td>
                  <td>⭐⭐</td>
                </tr>
                <tr>
                  <td>Rails</td>
                  <td>⭐⭐⭐</td>
                </tr>
              </table>
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
