import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>The Who</h1>
        <br/>
        <br/>
        <h2>Seems like you would like to know a little more than that little blurb</h2>
        <br/>
        <br/>
        <p className={styles.card}>
            Hi again. I'm Daniela. I'm a toddler mom and am navigating motherhood and a career change - talk about being brave. 
            I am blessed with an amazing husband, family and friends who suport me so much. 
            <br/>
            I was born and raised in Johannesburg, South Africa, and am proud of my Portguese roots and
            South African heritage. 
            <br/>
        </p>
      </main>
    </div>
  );
}
